repos:
  - repo: local
    hooks:
      - id: remove-index-lock
        name: remove-index-lock
        language: system
        entry: bash -c "rm -f .git/index.lock"
        always_run: true
      - id: poetry-export
        name: poetry-export
        language: system
        entry: bash scripts/poetry_export.sh
        always_run: true
