version: "3.9"

services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fault_tolerant_online_store
    ports:
      - "5432:5432"