version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8000"
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
  nginx-proxy:
    image: bitnami/nginx:latest
    volumes:
      - ./conf/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app